apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: example-dev

resources:
- namespace.yaml
- deployment.yaml

configMapGenerator:
- name: example-nginx
  files:
  - example-nginx